### ISSUE TITLE
外观：插件颜色自定义

### ISSUE THREAD

**Issue by jdjshhc** [a-nano-dust/dust-obsidian-calendar#33]
插件的默认颜色是蓝色

1. 然后是否可以根据主题颜色显示不想对应的颜色
2. 自己选择修改颜色，不受主题影响

**Comment by jdjshhc** [comment]
第一个主色调我也是自己修改了css，效果和你的一样，深色模式其实是满足要求的。就是浅色模式，字体颜色是黑色的跟主色调非常不搭，就没继续改了。

**Comment by Moyf** [comment]
> 第一个主色调我也是自己修改了css，效果和你的一样，深色模式其实是满足要求的。就是浅色模式，字体颜色是黑色的跟主色调非常不搭，就没继续改了。

深浅主题可以用 `.theme-dark` 和 `.theme-light` 区分。

例：
```css
.theme-dark .callout > .callout-title {
    background-color: #191919;
} 

.theme-light .callout > .callout-title {
    background-color: #FFF;
```
